joints:
  link_body_1:
    type: position
    amplitude: 0.1
    frequency: 2
    phase: 0.0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_2:
    type: position
    amplitude: 0.13636363636363638
    frequency: 2
    phase: 0.5711986642890533
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_3:
    type: position
    amplitude: 0.17272727272727273
    frequency: 2
    phase: 1.1423973285781066
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_4:
    type: position
    amplitude: 0.2090909090909091
    frequency: 2
    phase: 1.7135959928671598
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_5:
    type: position
    amplitude: 0.24545454545454548
    frequency: 2
    phase: 2.284794657156213
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_6:
    type: position
    amplitude: 0.28181818181818186
    frequency: 2
    phase: 2.8559933214452666
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_7:
    type: position
    amplitude: 0.31818181818181823
    frequency: 2
    phase: 3.4271919857343196
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_8:
    type: position
    amplitude: 0.3545454545454546
    frequency: 2
    phase: 3.998390650023373
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_9:
    type: position
    amplitude: 0.390909090909091
    frequency: 2
    phase: 4.569589314312426
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_10:
    type: position
    amplitude: 0.42727272727272725
    frequency: 2
    phase: 5.140787978601479
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_body_11:
    type: position
    amplitude: 0.4636363636363636
    frequency: 2
    phase: 5.711986642890533
    bias: 0
    pid:
      position:
        p: 10.0
        i: 0
        d: 0
      velocity:
        p: 0.01
        i: 0
        d: 0
  link_leg_0_L_0:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: -1.2566370614359172
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_0_L_1:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_0_L_2:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_0_R_0:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: -1.2566370614359172
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_0_R_1:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_0_R_2:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_1_L_0:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: -1.2566370614359172
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_1_L_1:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_1_L_2:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_1_R_0:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: -1.2566370614359172
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_1_R_1:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
  link_leg_1_R_2:
    type: position
    amplitude: 0.0
    frequency: 0
    phase: 0
    bias: 0
    pid:
      position:
        p: 10.0
        i: 1.0
        d: 0
      velocity:
        p: 0.001
        i: 0.0001
        d: 0
