# Package configuration
creator:
  author: "Jonathan Arreguit"
  email: "jonathan.arreguitoneill@epfl.ch"
gazebo:
  models_path: ".gazebo/models/"
model:
  name: "{{name}}"
  model_name: "{{model_name}}"
  base_model: "{{base_model}}"
  sdf_name: "{{model_name}}.sdf"
  config_name: "model.config"
  plugins:
    {{plugins|indent(4)}}
  version: "0.1"
