
island:
    topology:
        mixed: False
        full: False
        single: True
    number: 8

population: 
    size: 5
    seed:

save:
    save_on: 0
    save_off: 1
    interval: 100

migration:
  selection_policy:
    isl_best_policy: True
    isl_worst_policy: False
    isl_rand_policy: False
    archi_best_policy: False
  migration_on: False
  probability: 100
  scheme:
    matrix: False
    ring: False
    rand: True
    full: False
    low_density: False
  adjacency_matrix: [[0., 1., 1., 1., 1., 1., 1., 1.],
                   [0., 0., 1., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 1., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 1., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 1., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 1., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 1.],
                   [1., 0., 0., 0., 0., 0., 0., 0.]]

verbosity:
    print_interval: 2

algorithm_params:
    name_A: cmaes
    name_B:
    name_C:
    name_D:
    name_E:
    name_F:
    name_G:
    verbosity: False
    generation: 3

algorithm:
    de: 
        Muta_fac: 0.8
        CR_fac: 0.9
        variant: 2
        ftol: 0.000001
        xtol: 0.000001
    sga:
        CR_fac: 0.9
        eta_c: 1.0
        Muta_prob: 0.02
        param_m: 1.0
        param_s: 2
        crossover: exponential
        mutation: polynomial
        selection: tournament
    cmaes:
        cc: -1
        cs: -1
        c1: -1
        cmu: -1
        sigma0: 0.5
        ftol: 0.000001
        xtol: 0.000001
        memory: False
        force_bounds: False
        seed:
    psogen:
        omega: 0.7298
        eta1: 2.05
        eta2: 2.05
        max_vel: 0.5
        variant: 5
        neighb_type: 2
        neighb_param: 4
        memory: False
        seed:
    xnes:
        eta_mu: -1
        eta_sigma: -1
        eta_b: -1
        sigma0: -1
        ftol: 0.000001
        xtol: 0.000001
        memory: False
        force_bounds: False
        seed:
    nsga2:
        cr: 0.95
        eta_c: 10
        m: 0.01
        eta_m: 10
        seed:
    moead:
        weight_generation: grid
        decomposition: tchebycheff
        neighbours: 20
        CR: 1
        F: 0.5
        eta_m: 20
        realb: 0.9
        limit: 2
        preserve_diversity: True
        seed:
    sade:
        variant: 2
        variant_adptv: 1
        ftol: 0.000001
        xtol: 0.000001
        memory: False
    pso:
        omega:  0.7298
        eta1: 2.05 
        eta2: 2.05 
        max_vel: 0.5 
        variant: 5 
        neighb_type: 2 
        neighb_param: 4 
        memory: False
    bee_colony:
        limit: 20
    de1220:
        allowed_variants: [2,3,7,10,13,14,15,16]
        variant_adptv: 1 
        ftol: 0.000001
        xtol: 0.000001
        memory: False 
problem:
    name: schwefel
    dimension:
        lower:
        upper:
    fitness:

    
model:
    name:
    initial_condition:
    parameters:

figure:
    confidence_interval: 2
